name: scrape-models
on:
  push:
    branches:
      - "ci/*"
  schedule:
    - cron: "2,17,32,47 * * * *"
jobs:
  scrape:
    environment: Production
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - run: echo "TEMP_DIR=$(mktemp -d)" >> $GITHUB_ENV
      - name: Scrape models
        run: npx ts-node -T scripts/ci/scrape-models.ts
