name: scrape-scores-preview
on:
  push:
    branches:
      - "ci/*"
  schedule:
    - cron: "0 0 * * *"
jobs:
  scrape:
    environment: Production
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.PREVIEW_DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Scrape scores
        run: npx ts-node -T scripts/ci/scrape-scores.ts
